services:

    postgres:
        container_name: chatter_tool_postgres
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    redis:
        container_name: chatter_tool_redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data